apiVersion: v1
kind: ReplicationController
metadata: 
  name: myapp-rc
  labels:
    app: myapp
    type: front-end 
spec:
  template: 
    metadata:
      name: myapp-rc
      labels:
        app: myapp
        type: front-end
    spec: 
      containers:
        - name: webserver
          image: nginx

  replicas: 3