apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: myapp
  labels: 
    app: myapp
    type: frontend-deployement

spec: 
  template:
    metadata:
      name: myapp
      labels: 
        app: myapp
        type: frontend-deployement
    spec:
      containers:
        - name: webserver
          image: nginx

  replicas: 3

  selector:
     matchLabels:
       app: myapp
    
